# Generated by Django 5.2.11 on 2026-02-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_driver_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='main.driver')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
